version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/package.json" # The directory where your package manager file is located
    schedule:
      interval: "daily" # Can be daily, weekly, or monthly
    commit-message:
      prefix: "deps" # Optional prefix for pull request commit messages
